### ISSUE TITLE
Plugin ineffective after upgrading to OS X 10.10.3

### ISSUE THREAD

**Issue by jonnyhsy** [zats/AdjustFontSize-Xcode-Plugin#13]
I downloaded the repo, build and restart the Xcode, but Command + "+"/"-" doesn't work.

**Comment by zats** [comment]
Do you see the "Font Size" item added all the way at the bottom of the View menu?
Can you please run `$ defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID` and post the result here?

**Comment by chrisschreiner** [comment]
defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID 
=>
9F75337B-21B4-4ADC-B558-F9CADF7073A7

**Comment by zats** [comment]
@chrisschreiner do you have the same problem? do you see the menu items, mentioned above?

**Comment by chrisschreiner** [comment]
No, I don't see the menu items.

**Comment by zats** [comment]
Ah, you probably want to reinstall the plugin, sadly currently there is no better way to update it, but you can see the compatibility with 9F75337B-21B4-4ADC-B558-F9CADF7073A7 is in `master`

**Comment by jonnyhsy** [comment]
Hello zats,

I see the same UUID as chris mentioned, do you mean by re-installing the plugin would solve the issue? I see here's an update 4 days ago. Let me have a try.

**Comment by jonnyhsy** [comment]
Hello zats,

I could confirm that after pulling the newest source code and re-building it, it works fine. Thanks all!

**Comment by zats** [comment]
Glad it helped!
