### ISSUE TITLE
Xcode 7.2 not supported

### ISSUE THREAD

**Issue by hyouuu** [zats/AdjustFontSize-Xcode-Plugin#24]
As title, reinstall using Alcatraz doesn't help :(

**Comment by skipadu** [comment]
Adding new value for the 7.2 version into **Info.plist** solves the problem:
F41BD31E-2683-44B8-AE7F-5F09E919790E

Just few hours ago I downloaded the 7.2 version of Xcode and ran to non-working AdjustFontSize. After adding this new value to **Ino.plist** and rebuilded it, it started working like a charm.

(Looked the instructions to do it from here: https://github.com/robbiehanson/XcodeColors/wiki/XcodeUpdates#the-manual-way)

**Comment by skipadu** [comment]
hyouuu: Above change is now merged in the repository, so you can get it when you get the newest version.

**Comment by zats** [comment]
thanks both for reporting and for PR! 🍰
