### ISSUE TITLE
crash in xcode7.2

### ISSUE THREAD

**Issue by dimohamdy** [zats/AdjustFontSize-Xcode-Plugin#29]
when i try use it xcode 7.2 crash

**Comment by zats** [comment]
Sorry about that!
Any chance you can post the crash report here?

**Comment by GadgetAddict** [comment]
After I run it,  and then stop it....  the command plus or minus has no affect and I get these warnings

/Users/michael/Downloads/AdjustFontSize-Xcode-Plugin-master/AdjustFontSize/ZTSAdjustFontSize.m:224:41: PerformSelector may cause a leak because its selector is unknown

**Comment by zats** [comment]
Fixed perform selector warning, please note the hotkey binding was also updated to avoid conflicts with interface builder.
Please reopen the issue if there is still a problem

**Comment by dimohamdy** [comment]
@zats Thanks
