### ISSUE TITLE
How to use Simply hit ⌃ = or ⌃ - ?

### ISSUE THREAD

**Issue by arvindmuthu** [zats/AdjustFontSize-Xcode-Plugin#30]
Hi there....
Its a very good plugin to be used for Xcode...
But sorry for asking a silly question...how to hot ⌃ = or ⌃ - ?

I tried shift+^ and = ...and many other to use the shortcut but not working....
I can able to use this via view--> font size--> increase/decrease...thats work fine...

your prompt reply is highly appreciated...thx in advance..

**Comment by micnguyen** [comment]
I had the same issue. This really should be Command + -/+ rather than ^. ^ makes it seem like you have to hold down shift + 6.

**Comment by zats** [comment]
Oh sorry, my bad, the symbol looking like carrot stands for `Control` key, I'll make sure to update the readme
