### ISSUE TITLE
Could you please add the keybindings to Xcode keybindings panel ?

### ISSUE THREAD

**Issue by Daopr** [zats/AdjustFontSize-Xcode-Plugin#31]
Could you please add the keybindings to Xcode keybindings panel ? I wanna use Command - & Command + as shorcuts

**Comment by ForrestAlfred** [comment]
.

**Comment by zats** [comment]
Hi, thanks for suggestion! I'll look into it.

**Comment by agentk** [comment]
P.S. @zats As a temp solution, keybindings can be changed using System Preferences -> Keyboard -> Shorcuts -> App Shortcuts. You can add the following screen shot to the Readme if it helps.

<img width="668" alt="screen shot 2016-06-10 at 10 32 32 pm" src="https://cloud.githubusercontent.com/assets/117041/15964393/ade650ee-2f5b-11e6-9bf4-87a1ebe8ddcf.png">

**Comment by zats** [comment]
That's a great idea! Thanks!

**Comment by zats** [comment]
Thanks @agentk once again! I used your screenshot in readme. Hope you don't mind!

**Comment by agentk** [comment]
Not a problem at all. I hope it helps relieve some of the keybinding questions for you. I make use of this plugin every single day. Keep up the good work.
