### ISSUE TITLE
Is there a way to change the hotkeys?

### ISSUE THREAD

**Issue by nikitavoloboev** [zats/AdjustFontSize-Xcode-Plugin#34]
I would like to change it from ⌃+ and ⌃- to ⌃⌥+ and ⌃⌥-.

Can I do that?

**Comment by zats** [comment]
Currently there is no way without building plugin manually. If you do want it, you can change hotkeys here: https://github.com/zats/AdjustFontSize-Xcode-Plugin/blob/master/AdjustFontSize/ZTSAdjustFontSize.m#L139-L149

**Comment by nikitavoloboev** [comment]
thank you, that worked :)

**Comment by zats** [comment]
Glad it helped!😊 Sorry there is no better solution for now😬
