### ISSUE TITLE
Should plugin description be updated in Alcatraz?

### ISSUE THREAD

**Issue by rrecio** [zats/AdjustFontSize-Xcode-Plugin#35]
<img width="1440" alt="fullscreen_5_29_16__2_40_pm" src="https://cloud.githubusercontent.com/assets/52694/15635093/d34fe340-25ab-11e6-877a-6a2e6870b980.png">

**Comment by zats** [comment]
Hi, thanks for the pointer, you can track the issue progress in this PR https://github.com/alcatraz/alcatraz-packages/pull/585

**Comment by zats** [comment]
@rrecio it was merged, thanks for reporting! 🍰

**Comment by rrecio** [comment]
I'm glad to help :D

Enviado do meu iPhone
