### ISSUE TITLE
Does this work with XCode 8?

### ISSUE THREAD

**Issue by mattnedrich** [zats/AdjustFontSize-Xcode-Plugin#36]
I'm trying to run this with XCode 8. My XCode 8 is stored at `/Applications/XCode_8` instead of `/Applications/XCode`, should this make a difference? Not sure if this has any dependencies on the xcode toolchain, but I update that (via `xcode-select`) to point to XCode 8 before running this project. It crashes with this error:

`DVTAssertions: UNCAUGHT EXCEPTION (NSInternalInconsistencyException): The loaded com.apple.CoreSimulator.CoreSimulatorService job does not match our expectations: pathOfLoadedJob: /Applications/Xcode_8.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/com.apple.CoreSimulator.CoreSimulatorService.xpc/Contents/MacOS/com.apple.CoreSimulator.CoreSimulatorService, our frameworkPath: /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework`

The framework path seems wrong.

**Comment by jonchoi** [comment]
I'm having some issues with Xcode 8.1 as well.

**Comment by zats** [comment]
hey, sorry it took me ages to respond. 
basically plugins are not officially supported with Xcode 8, hence I didn't plan to continue development
There is a way to enable Xcode loading plugins but it reduces security and involves so-called "unsigning" you can look into that if you are interested in using plugins
