### ISSUE TITLE
Extend support to non code editor windows/views

### ISSUE THREAD

**Issue by mike-lischke** [zats/AdjustFontSize-Xcode-Plugin#9]
Please extend the support for this very useful plugin so we can also change the font size for inspectors, file list etc.

**Comment by zats** [comment]
@allewun added support for console (merged in master from PR #10)

**Comment by khs8727** [comment]
for storyboard (zoom in/out) too. The command doesn't work since I installed this plugin.

**Comment by khalidchawtany** [comment]
After installing this, the default zoom functionality of storyboard is broken!

**Comment by zats** [comment]
Oh that must be due to a conflict in hotkeys, thank you for reporting!

**Comment by khalidchawtany** [comment]
I don't know how those keys can be changed. They don't appear in the settings window, if I am not mistaken. Can you tell us how to change them?
Thanks lovely extension :+1:

**Comment by zats** [comment]
sadly, it is not customisable at the moment, I'll take a look at what it takes to make it customisable
a workaround at the moment is:

1. Download the plugin project locally 
2. Modify these lines to any shortcuts you prefer https://github.com/zats/AdjustFontSize-Xcode-Plugin/blob/master/AdjustFontSize/ZTSAdjustFontSize.m#L139-L146
3. Press `⌘B` to build
4. Restart Xcode

**Comment by khalidchawtany** [comment]
@zats Thanks

**Comment by zats** [comment]
I'm closing this issue as it became a "catch all" issue in a sense😁
The issue with hotkey conflict is fixed.
Note there hotkey binding has been changed to avoid conflict with Interface Builder
Please open a separate issue if you still experience any problems
Thanks everyone!
